name: /conda_envs/gnn_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - aom=3.6.1=h59595ed_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.2=h3394656_1
  - cartopy=0.24.0=py311h7db5c69_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311hd18a35c_0
  - cpython=3.11.11=py311hd8ed1ab_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - cvxopt=1.3.2=py311he0106dc_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - cython=3.0.11=py311h55d416d_3
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h59595ed_0
  - dsdp=5.8=hd9d9efa_1203
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.16.1=pyhd8ed1ab_1
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py311h2dc5d0c_0
  - freetype=2.12.1=h267a509_2
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.13.0=h5888daf_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_3
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.4=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libamd=3.3.3=ss783_h889e182
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libbtf=2.3.2=ss783_h2377355
  - libcamd=3.3.3=ss783_h2377355
  - libcblas=3.9.0=16_linux64_mkl
  - libccolamd=3.3.4=ss783_h2377355
  - libcholmod=5.3.0=ss783_h3fa60b6
  - libclang-cpp19.1=19.1.5=default_hb5137d0_0
  - libclang13=19.1.5=default_h9c6a7e4_0
  - libcolamd=3.3.4=ss783_h2377355
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.7.77=0
  - libcurl=8.11.1=h332b0f4_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcxsparse=4.4.1=ss783_h2377355
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libklu=2.3.5=ss783_hfbdfdfc
  - liblapack=3.9.0=16_linux64_mkl
  - libldl=3.3.2=ss783_h2377355
  - libllvm19=19.1.5=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libnvjpeg=11.9.0.86=0
  - libopengl=1.7.0=ha4b6fd6_2
  - libparu=1.0.0=ss783_h8814b27
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.2=h3b95a9b_1
  - librbio=4.3.4=ss783_h2377355
  - libsodium=1.0.20=h4ab18f5_0
  - libspex=3.2.1=ss783_h5a7e440
  - libspqr=4.3.4=ss783_hae1ff0d
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsuitesparseconfig=7.8.3=ss783_h83006af
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.7.0=hc4654cb_2
  - libumfpack=6.3.5=ss783_hd4f9ce1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.9.3=py311h38be061_0
  - matplotlib-base=3.9.3=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metis=5.1.0=hd0bcaf9_1007
  - metpy=1.6.3=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_3
  - mysql-libs=9.0.1=he0572af_3
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=pyh267e887_2
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311h7db5c69_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py311h49e9ac3_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.5.1=h0054346_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyproj=3.7.0=py311h0f98d5a_0
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pyside6=6.8.0.2=py311h9053184_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.11=5_cp311
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h9ecbd09_1
  - pyzmq=26.4.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.0=h6e8976b_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-learn=1.6.0=py311h57cc02b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.6.0=pyhff2d567_1
  - shapely=2.0.6=py311h2fdb869_2
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.47.2=h9eae976_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311hb0beb2c_0
  - suitesparse=7.8.3=ss783_h36e971b
  - svt-av1=1.4.1=hcb278e6_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.5.1=py311_cu118
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu118
  - tornado=6.4.2=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py311h9ecbd09_1
  - urllib3=2.2.3=pyhd8ed1ab_1
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2024.11.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_2
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_4
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - branca==0.8.1
      - captum==0.8.0
      - folium==0.19.5
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - multidict==6.6.3
      - narwhals==1.41.0
      - numpy==1.26.4
      - plotly==6.1.2
      - propcache==0.3.2
      - pyg-lib==0.4.0+pt25cu118
      - pytorch-tcn==1.2.1
      - scipy==1.15.3
      - sympy==1.13.1
      - torch-cluster==1.6.3+pt25cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu118
      - torch-sparse==0.6.18+pt25cu118
      - torch-spline-conv==1.2.2+pt25cu118
      - windrose==1.9.2
      - xyzservices==2025.1.0
      - yarl==1.20.1
prefix: /pscratch/sd/r/rdimri/conda_envs/gnn_env
